const Intents = [
    "READY",
    "RESUMED",
    "VOICE_SERVER_UPDATE",
    "USER_UPDATE",
    "APPLICATION_COMMAND_CREATE",
    "APPLICATION_COMMAND_UPDATE",
    "APPLICATION_COMMAND_DELETE",
    "INTERACTION_CREATE",
    "GUILD_CREATE",
    "GUILD_DELETE",
    "GUILD_ROLE_CREATE",
    "GUILD_ROLE_UPDATE",
    "GUILD_ROLE_DELETE",
    "THREAD_CREATE",
    "THREAD_UPDATE",
    "THREAD_DELETE",
    "THREAD_LIST_SYNC",
    "THREAD_MEMBER_UPDATE",
    "THREAD_MEMBERS_UPDATE",
    "CHANNEL_CREATE",
    "CHANNEL_UPDATE",
    "CHANNEL_DELETE",
    "CHANNEL_PINS_UPDATE",
    "GUILD_MEMBER_ADD",
    "GUILD_MEMBER_UPDATE",
    "GUILD_MEMBER_REMOVE",
    "GUILD_BAN_ADD",
    "GUILD_BAN_REMOVE",
    "GUILD_WEBHOOKS_UPDATE",
    "MESSAGE_CREATE",
    "MESSAGE_UPDATE",
    "MESSAGE_DELETE",
    "MESSAGE_DELETE_BULK",
    "MESSAGE_REACTION_ADD",
    "MESSAGE_REACTION_REMOVE",
    "MESSAGE_REACTION_REMOVE_ALL",
    "MESSAGE_REACTION_REMOVE_EMOJI",
]

const Colors = {
    Default: 0x000000,
    White: 0xffffff,
    Aqua: 0x1abc9c,
    Green: 0x57f287,
    Blue: 0x3498db,
    Yellow: 0xfee75c,
    Purple: 0x9b59b6,
    LuminousVividPink: 0xe91e63,
    Fuchsia: 0xeb459e,
    Gold: 0xf1c40f,
    Orange: 0xe67e22,
    Red: 0xed4245,
    Grey: 0x95a5a6,
    Navy: 0x34495e,
    DarkAqua: 0x11806a,
    DarkGreen: 0x1f8b4c,
    DarkBlue: 0x206694,
    DarkPurple: 0x71368a,
    DarkVividPink: 0xad1457,
    DarkGold: 0xc27c0e,
    DarkOrange: 0xa84300,
    DarkRed: 0x992d22,
    DarkGrey: 0x979c9f,
    DarkerGrey: 0x7f8c8d,
    LightGrey: 0xbcc0c0,
    DarkNavy: 0x2c3e50,
    Blurple: 0x5865f2,
    Greyple: 0x99aab5,
    DarkButNotBlack: 0x2c2f33,
    NotQuiteBlack: 0x23272a,
}

const ColorsTranslate = {
    Default: "Padrão",
    White: "Branco",
    Aqua: "Água",
    Green: "Verde",
    Blue: "Azul",
    Yellow: "Amarelo",
    Purple: "Roxo",
    LuminousVividPink: "Rosa Vívido Luminoso",
    Fuchsia: "Fuchsia",
    Gold: "Ouro",
    Orange: "Laranja",
    Red: "Vermelho",
    Grey: "Cinza",
    Navy: "Oceano Apagado",
    DarkAqua: "Água Escura",
    DarkGreen: "Verde Escuro",
    DarkBlue: "Azul Escuro",
    DarkPurple: "Roxo Escuro",
    DarkVividPink: "Rosa Vívido Escuro",
    DarkGold: "Ouro Escuro",
    DarkOrange: "Laranja Escuro",
    DarkRed: "Vermelho Escuro",
    DarkGrey: "Cinza Escuro",
    DarkerGrey: "Cinza Mais Escuro",
    LightGrey: "Cinza Claro",
    DarkNavy: "Oceano Escuro",
    Blurple: "Violeta",
    Greyple: "Verde Acinzentado",
    DarkButNotBlack: "Escuro, mas não preto",
    NotQuiteBlack: "Não tão preto"
  }

const Events = {
    ApplicationCommandPermissionsUpdate: 'applicationCommandPermissionsUpdate',
    CacheSweep: 'cacheSweep',
    ChannelCreate: 'channelCreate',
    ChannelDelete: 'channelDelete',
    ChannelPinsUpdate: 'channelPinsUpdate',
    ChannelUpdate: 'channelUpdate',
    ClientReady: 'ready',
    Debug: 'debug',
    Error: 'error',
    GuildBanAdd: 'guildBanAdd',
    GuildBanRemove: 'guildBanRemove',
    GuildCreate: 'guildCreate',
    GuildDelete: 'guildDelete',
    GuildEmojiCreate: 'emojiCreate',
    GuildEmojiDelete: 'emojiDelete',
    GuildEmojiUpdate: 'emojiUpdate',
    GuildIntegrationsUpdate: 'guildIntegrationsUpdate',
    GuildMemberAdd: 'guildMemberAdd',
    GuildMemberAvailable: 'guildMemberAvailable',
    GuildMemberRemove: 'guildMemberRemove',
    GuildMembersChunk: 'guildMembersChunk',
    GuildMemberUpdate: 'guildMemberUpdate',
    GuildRoleCreate: 'roleCreate',
    GuildRoleDelete: 'roleDelete',
    GuildRoleUpdate: 'roleUpdate',
    GuildScheduledEventCreate: 'guildScheduledEventCreate',
    GuildScheduledEventDelete: 'guildScheduledEventDelete',
    GuildScheduledEventUpdate: 'guildScheduledEventUpdate',
    GuildScheduledEventUserAdd: 'guildScheduledEventUserAdd',
    GuildScheduledEventUserRemove: 'guildScheduledEventUserRemove',
    GuildStickerCreate: 'stickerCreate',
    GuildStickerDelete: 'stickerDelete',
    GuildStickerUpdate: 'stickerUpdate',
    GuildUnavailable: 'guildUnavailable',
    GuildUpdate: 'guildUpdate',
    InteractionCreate: 'interactionCreate',
    Invalidated: 'invalidated',
    InviteCreate: 'inviteCreate',
    InviteDelete: 'inviteDelete',
    MessageBulkDelete: 'messageDeleteBulk',
    MessageCreate: 'messageCreate',
    MessageDelete: 'messageDelete',
    MessageReactionAdd: 'messageReactionAdd',
    MessageReactionRemove: 'messageReactionRemove',
    MessageReactionRemoveAll: 'messageReactionRemoveAll',
    MessageReactionRemoveEmoji: 'messageReactionRemoveEmoji',
    MessageUpdate: 'messageUpdate',
    PresenceUpdate: 'presenceUpdate',
    Raw: 'raw',
    ShardDisconnect: 'shardDisconnect',
    ShardError: 'shardError',
    ShardReady: 'shardReady',
    ShardReconnecting: 'shardReconnecting',
    ShardResume: 'shardResume',
    StageInstanceCreate: 'stageInstanceCreate',
    StageInstanceDelete: 'stageInstanceDelete',
    StageInstanceUpdate: 'stageInstanceUpdate',
    ThreadCreate: 'threadCreate',
    ThreadDelete: 'threadDelete',
    ThreadListSync: 'threadListSync',
    ThreadMembersUpdate: 'threadMembersUpdate',
    ThreadMemberUpdate: 'threadMemberUpdate',
    ThreadUpdate: 'threadUpdate',
    TypingStart: 'typingStart',
    UserUpdate: 'userUpdate',
    VoiceServerUpdate: 'voiceServerUpdate',
    VoiceStateUpdate: 'voiceStateUpdate',
    Warn: 'warn',
    WebhooksUpdate: 'webhookUpdate',
}

const ShardEvents = {
    Close: 'close',
    Destroyed: 'destroyed',
    InvalidSession: 'invalidSession',
    Ready: 'ready',
    Resumed: 'resumed',
    AllReady: 'allReady',
}

const Permissions = {
    CREATE_INSTANT_INVITE: "Criar convite",
    KICK_MEMBERS: "Expulsar membros",
    BAN_MEMBERS: "Banir membros",
    ADMINISTRATOR: "Administrador",
    MANAGE_CHANNELS: "Gerenciar canais",
    MANAGE_GUILD: "Gerenciar servidor",
    ADD_REACTIONS: "Adicionar reações",
    VIEW_AUDIT_LOG: "Ver o registro de auditoria",
    PRIORITY_SPEAKER: "Voz Prioritária",
    STREAM: "Vídeo",
    VIEW_CHANNEL: "Ver canais",
    SEND_MESSAGES: "Enviar mensagens",
    SEND_TTS_MESSAGES: "Enviar mensagens TTS",
    MANAGE_MESSAGES: "Gerenciar mensagens",
    EMBED_LINKS: "Enviar links",
    ATTACH_FILES: "Enviar arquivos",
    READ_MESSAGE_HISTORY: "Ver histórico de mensagens",
    MENTION_EVERYONE: "Mencionar Everyone",
    USE_EXTERNAL_EMOJIS: "Usar emojis externos",
    VIEW_GUILD_INSIGHTS: "Ver Análises do Servidor",
    CONNECT: "Conectar",
    SPEAK: "Falar",
    MUTE_MEMBERS: "Silenciar membros",
    DEAFEN_MEMBERS: "Ensurdecer membros",
    MOVE_MEMBERS: "Mover membros",
    USE_VAD: "Usar detecção de voz",
    CHANGE_NICKNAME: "Mudar apelido",
    MANAGE_NICKNAMES: "Gerenciar apelidos",
    MANAGE_ROLES: "Gerenciar cargos",
    MANAGE_WEBHOOKS: "Gerenciar Webhooks",
    MANAGE_EMOJIS_AND_STICKERS: "Gerenciar emojis e figurinhas",
    USE_APPLICATION_COMMANDS: "Usar comandos de aplicativos",
    REQUEST_TO_SPEAK: "Pedir para falar",
    MANAGE_THREADS: "Gerenciar Threads",
    USE_PUBLIC_THREADS: "Usar threads publicas",
    USE_PRIVATE_THREADS: "Usar threads privadas",
    USE_EXTERNAL_STICKERS: "Usar figurinhas externas",
    START_EMBEDDED_ACTIVITIES: "Começar atividades embedded",
    SEND_MESSAGES_IN_THREADS: "Enviar mensagens em threads",
    CREATE_PRIVATE_THREADS: "Criar threads privadas",
    CREATE_PUBLIC_THREADS: "Criar threads publicas",
    MODERATE_MEMBERS: "Moderar membros"
}

module.exports = { Intents, Colors, Events, ShardEvents, ColorsTranslate, Permissions }