const { Schema, model } = require("mongoose")

module.exports = model("User", new Schema({
    id: { type: String, unique: true },
    Timeouts: {
        Bug: Number,
        Daily: Number,
        Monthly: Number,
        Weekly: Number,
        Cu: Number,
        Roleta: Number,
        Esmola: Number,
        Work: Number,
        ImagesCooldown: Number,
        ServerIdeia: Number,
        Letter: Number,
        Confess: Number,
        Loteria: Number,
        LevelTrade: Number,
        LevelImage: Number,
        Cantada: Number,
        Bitcoin: Number,
        Porquinho: Number,
        Rep: Number,
        Bolsa: Number,
    },
    Cache: {
        ComprovanteOpen: Boolean,
        Assalto: Number,
        BetPrize: Number,
        BingoPrize: Number,
        Resgate: Number,
        Bolsa: Number,
        BolsaValue: Number,
        BolsaEmpresa: String,
        BolsaLucro: Number,
        LancePrize: Number,
        Pay: Number,
        Duelo: Number,
        Pix: Number,
        ValueAll: Number,
    },
    Color: {
        Perm: Boolean,
        Set: String
    },
    Perfil: {
        TitlePerm: Boolean,
        Titulo: String,
        Status: String,
        Sexo: String,
        Signo: String,
        Aniversario: String,
        Trabalho: String,
        BalanceOcult: Boolean,
        Family: {
            Um: String,
            Dois: String,
            Tres: String,
        },
        Marry: String,
        Bits: Number,
        Bitcoins: Number,
        Estrela: {
            Um: Boolean,
            Dois: Boolean,
            Tres: Boolean,
            Quatro: Boolean,
            Cinco: Boolean,
            Seis: Boolean,
        },
        Parcas: { // TODO: Colocar parças em array
            Um: String,
            Dois: String,
            Tres: String,
            Quatro: String,
            Cinco: String,
        }
    },
    Vip: {
        DateNow: Number,
        TimeRemaing: Number,
        Permanent: Boolean
    },
    Slot: {
        TitlePerm: String,
        Cartas: Number,
        Anel: Boolean,
        Dogname: String,
    },
    Clan: String,
    Likes: Number,
    Xp: Number,
    Level: Number,
    Balance: Number,
    AfkSystem: String,
    Walls: {
        Bg: { type: Array, default: undefined },
        Set: String
    },
    PrivateChannel: String,
    NoReact: Boolean,
    Transactions: { type: Array, default: undefined }
}))